/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kiosco;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author Diego
 */
public class Consultar_pedido extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form Consultar_pedido
     */
    String hora, minutos,segundos;
    Thread hilo;
    public String primerplato, segundoplato, postreplato, bebidadef;
    ventana v=new ventana();
    ArrayList<String> pedidos = new ArrayList<String>();
    ArrayList<Integer> precios = new ArrayList<Integer>();
    int precio=0;
    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }
    
    public Consultar_pedido( ArrayList<String> lista, ArrayList<Integer> listap) {
        initComponents();
        pedidos = lista;
        precios = listap;
        lbdia.setText (Fecha ());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        if (lista.isEmpty() == true){
            TA_pedido.append(System.getProperty("line.separator"));
            TA_pedido.append("No hay ningún pedido");
        } else {
            for (int i=0; i< lista.size(); i++){
                TA_pedido.append(System.getProperty("line.separator"));
                TA_pedido.append(String.valueOf(i+1)+". ");
                TA_pedido.append(lista.get(i));
                
                precio = precio + precios.get(i);
            }
        }
        String precio_final = Integer.toString(precio);
        pago_final.setText(precio_final+"€");
    }
    
    public void Hora(){
        Calendar calendario = new GregorianCalendar ();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }

    public void run(){
        Thread current = Thread.currentThread();
        while (current ==hilo){
            Hora();
            lbhora.setText(hora+":"+minutos+":"+segundos);
        }
    }
    
    public static String Fecha(){
        Date fecha = new Date ();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jButton1 = new javax.swing.JButton();
        Pagar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_pedido = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pago_final = new javax.swing.JLabel();
        erro = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        lbdia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Pedir algo más");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        Pagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pagar.setText("Continuar con el pagamiento");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });
        add(Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Modificar pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        TA_pedido.setColumns(20);
        TA_pedido.setRows(5);
        TA_pedido.setText("Su pedido consta de:");
        TA_pedido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TA_pedidoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TA_pedido);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 469, 115));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Consulta tu pedido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Importe final: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        pago_final.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(pago_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, 30));

        erro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        erro.setForeground(new java.awt.Color(255, 0, 0));
        add(erro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        lbhora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbhora.setText("00:00:00");
        add(lbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        lbdia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdia.setText("MM/DD/YYYY");
        add(lbdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("-");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Pide pp=new Pide(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        // TODO add your handling code here:
        if (pedidos.isEmpty()==false){
            this.v.getContentPane().setVisible(false);
            Acabar_pedir pp=new Acabar_pedir(pedidos, precios);
            pp.setVisible(true);
            pp.setV(this.v);
            this.v.setContentPane(pp);
        } else {
            erro.setText("Selecciona algún producto");
        }
        
    }//GEN-LAST:event_PagarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (pedidos.isEmpty()==false){
            this.v.getContentPane().setVisible(false);
            Modificar_pedido pp=new Modificar_pedido(pedidos, precios);
            pp.setVisible(true);
            pp.setV(this.v);
            this.v.setContentPane(pp);
        } else {
            erro.setText("Selecciona algún producto");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TA_pedidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TA_pedidoAncestorAdded
        // TODO add your handling code here:
        TA_pedido.setEditable(false);
    }//GEN-LAST:event_TA_pedidoAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pagar;
    private javax.swing.JTextArea TA_pedido;
    private javax.swing.JLabel erro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbdia;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel pago_final;
    // End of variables declaration//GEN-END:variables
}
