/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicial.java
 *
 * Created on 18-nov-2011, 12:51:01
 */
package Kiosco;

import java.util.ArrayList;

/**
 *
 * @author Pedro
 */
public class Inicio extends javax.swing.JPanel {

    /** Creates new form Inicial */
    ArrayList<String> pedidos = new ArrayList<String>();
    ArrayList<Integer> precios = new ArrayList<Integer>();
    private ventana v;

    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }

    public Inicio(ArrayList<String> lista, ArrayList<Integer> listap) {
        initComponents();
        pedidos = lista;
        precios = listap;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        castellano = new javax.swing.JButton();
        gallego = new javax.swing.JButton();
        aleman = new javax.swing.JButton();
        ingles = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido a ");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 0, -1, 37));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<html>\n<p>Haz click aquí para</p>\n<p>&nbsp; acceder al kiosco</p>\n</html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 128, 257, 152));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Restaurante O Último");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 43, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Horario: de 13:00 a 16:00 y de 20:00 a 23:00");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 329, -1, 31));

        castellano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Española.JPG"))); // NOI18N
        castellano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castellanoActionPerformed(evt);
            }
        });
        jPanel1.add(castellano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, 53, 41));

        gallego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gallega.JPG"))); // NOI18N
        gallego.setText("gallego");
        gallego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gallegoActionPerformed(evt);
            }
        });
        jPanel1.add(gallego, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 128, 53, 43));

        aleman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Alemana.JPG"))); // NOI18N
        aleman.setText("aleman");
        aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alemanActionPerformed(evt);
            }
        });
        jPanel1.add(aleman, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 236, 53, 44));

        ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inglesa.JPG"))); // NOI18N
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        jPanel1.add(ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 236, 53, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Consulta pp=new Consulta(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void castellanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castellanoActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Inicio pp=new Inicio(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_castellanoActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Inicio_ingles pp=new Inicio_ingles(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_inglesActionPerformed

    private void gallegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gallegoActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Inicio_gallego pp=new Inicio_gallego(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_gallegoActionPerformed

    private void alemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemanActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Inicio_aleman pp=new Inicio_aleman(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_alemanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aleman;
    private javax.swing.JButton castellano;
    private javax.swing.JButton gallego;
    private javax.swing.JButton ingles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
