/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kiosco;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Menu_dia_pide extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form Menu_dia_pide
     */
    String hora, minutos,segundos;
    Thread hilo;
    
    public String primero, segundo, postre, bebida, pedidofinal;
    
    ArrayList<String> pedidos = new ArrayList<String>();
    ArrayList<Integer> precios = new ArrayList<Integer>();
    String pedido;

    //Nuevos cambios
    
    //Hasta aquí
    
    ventana v=new ventana();
    
    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }
    
    public Menu_dia_pide(ArrayList<String> lista, ArrayList<Integer> listap) {
        initComponents();
        pedidos = lista;
        precios = listap;
        lbdia.setText (Fecha ());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }
        
    public void Hora(){
        Calendar calendario = new GregorianCalendar ();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }

    public void run(){
        Thread current = Thread.currentThread();
        while (current ==hilo){
            Hora();
            lbhora.setText(hora+":"+minutos+":"+segundos);
        }
    }
    
    public static String Fecha(){
        Date fecha = new Date ();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Boton11 = new javax.swing.JRadioButton();
        Boton12 = new javax.swing.JRadioButton();
        Boton13 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Boton21 = new javax.swing.JRadioButton();
        Boton23 = new javax.swing.JRadioButton();
        Boton22 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Boton31 = new javax.swing.JRadioButton();
        Boton32 = new javax.swing.JRadioButton();
        Boton33 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Boton41 = new javax.swing.JRadioButton();
        Boton42 = new javax.swing.JRadioButton();
        Boton43 = new javax.swing.JRadioButton();
        Boton44 = new javax.swing.JRadioButton();
        pedir = new javax.swing.JButton();
        lbdia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        erro = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(Boton11);
        Boton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton11.setText("Croquetas de jamón caseras");
        Boton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton11ActionPerformed(evt);
            }
        });
        add(Boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, -1, 30));

        buttonGroup1.add(Boton12);
        Boton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton12.setText("Ensaladilla rusa");
        Boton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton12ActionPerformed(evt);
            }
        });
        add(Boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 135, 30));

        buttonGroup1.add(Boton13);
        Boton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton13.setText("Pimientos de padrón");
        Boton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton13ActionPerformed(evt);
            }
        });
        add(Boton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Primer plato");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, -1, 20));

        buttonGroup2.add(Boton21);
        Boton21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton21.setText("Raxo con patatas");
        Boton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton21ActionPerformed(evt);
            }
        });
        add(Boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, 30));

        buttonGroup2.add(Boton23);
        Boton23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton23.setText("Zorza con patatas");
        Boton23.setActionCommand("Raxo con patatas");
        Boton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton23ActionPerformed(evt);
            }
        });
        add(Boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        buttonGroup2.add(Boton22);
        Boton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton22.setText("Chipirones con patatas y ensalada");
        Boton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton22ActionPerformed(evt);
            }
        });
        add(Boton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Segundo plato");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Postre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 194, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bebidas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 30));

        buttonGroup3.add(Boton31);
        Boton31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton31.setText("Helado de vainilla");
        Boton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton31ActionPerformed(evt);
            }
        });
        add(Boton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, 30));

        buttonGroup3.add(Boton32);
        Boton32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton32.setText("Tarta de la abuela");
        Boton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton32ActionPerformed(evt);
            }
        });
        add(Boton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, 30));

        buttonGroup3.add(Boton33);
        Boton33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton33.setText("Tarta de santiago");
        Boton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton33ActionPerformed(evt);
            }
        });
        add(Boton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Menú del día");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Solo puedes elegir una comida por plato");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        buttonGroup4.add(Boton41);
        Boton41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton41.setText("Agua");
        Boton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton41ActionPerformed(evt);
            }
        });
        add(Boton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 30));

        buttonGroup4.add(Boton42);
        Boton42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton42.setText("Refrescos");
        Boton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton42ActionPerformed(evt);
            }
        });
        add(Boton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, 30));

        buttonGroup4.add(Boton43);
        Boton43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton43.setText("Vino");
        Boton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton43ActionPerformed(evt);
            }
        });
        add(Boton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 30));

        buttonGroup4.add(Boton44);
        Boton44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton44.setText("Cerveza");
        Boton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton44ActionPerformed(evt);
            }
        });
        add(Boton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, 30));

        pedir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pedir.setText("Añadir al carrito");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });
        add(pedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        lbdia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdia.setText("MM/DD/YYYY");
        add(lbdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("-");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        lbhora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbhora.setText("00:00:00");
        add(lbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        erro.setForeground(new java.awt.Color(255, 51, 0));
        add(erro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("12€");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void Boton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton13ActionPerformed
        // TODO add your handling code here:
        if (Boton13.isSelected()){
            primero = "pimientos de padrón";
        }
        
    }//GEN-LAST:event_Boton13ActionPerformed

    private void Boton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton23ActionPerformed
        // TODO add your handling code here:
        if (Boton23.isSelected()){
            segundo = "zorza con patatas";
        } 
    }//GEN-LAST:event_Boton23ActionPerformed

    private void Boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton12ActionPerformed
        // TODO add your handling code here:
        if (Boton12.isSelected()){
            primero = "ensaladilla rusa";
        } 
    }//GEN-LAST:event_Boton12ActionPerformed

    private void Boton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton33ActionPerformed
        // TODO add your handling code here:
        if (Boton33.isSelected()){
            postre = "tarta de santiago";
        } 
    }//GEN-LAST:event_Boton33ActionPerformed
 
    
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        this.v.getContentPane().setVisible(false);
        Pide pp=new Pide(pedidos, precios);
        pp.setVisible(true);
        pp.setV(this.v);
        this.v.setContentPane(pp);
    }//GEN-LAST:event_VolverActionPerformed

    private void Boton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton11ActionPerformed
        // TODO add your handling code here
        if (Boton11.isSelected()){
            primero = "croquetas de jamón caseras";
        }
    }//GEN-LAST:event_Boton11ActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
        // TODO add your handling code here:
        if (Boton11.isSelected()==true || Boton12.isSelected()==true || Boton13.isSelected()==true){
            if (Boton21.isSelected()==true || Boton22.isSelected()==true || Boton23.isSelected()==true){
                if(Boton31.isSelected()==true || Boton32.isSelected()==true || Boton33.isSelected()==true){
                    if(Boton41.isSelected()==true || Boton42.isSelected()==true || Boton43.isSelected()==true || Boton44.isSelected()==true){
                        pedidofinal = "Menú del día: 12€\n " + primero + ", " + segundo + ", " + postre + ", \n" + bebida;
                        pedidos.add(pedidofinal);
                        precios.add(12);
                        this.v.getContentPane().setVisible(false);
                        Consultar_pedido pp=new Consultar_pedido(pedidos, precios);
                        pp.setVisible(true);
                        pp.setV(this.v);
                        this.v.setContentPane(pp); 
                    } else {
                        erro.setText("Seleccione una bebida");
                    }
                } else {
                    erro.setText("Seleccione un postre");
                }
            }else {
                erro.setText("Seleccione un segundo plato");
            }
        } else {
            erro.setText("Seleccione un primer plato");
        }
    }//GEN-LAST:event_pedirActionPerformed

    private void Boton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton31ActionPerformed
        // TODO add your handling code here:
        if (Boton31.isSelected()){
            postre = "helado de vainilla";
        } 
    }//GEN-LAST:event_Boton31ActionPerformed

    private void Boton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton32ActionPerformed
        // TODO add your handling code here:
        if (Boton32.isSelected()){
            postre = "tarta de la abuela";
        } 
    }//GEN-LAST:event_Boton32ActionPerformed

    private void Boton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton21ActionPerformed
        // TODO add your handling code here:
        if (Boton21.isSelected()){
            segundo = "raxo con patatas";
        } 
    }//GEN-LAST:event_Boton21ActionPerformed

    private void Boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton22ActionPerformed
        // TODO add your handling code here:
        if (Boton22.isSelected()){
            segundo = "chipirones con patatas y ensalada";
        } 
    }//GEN-LAST:event_Boton22ActionPerformed

    private void Boton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton41ActionPerformed
        // TODO add your handling code here:
        if (Boton41.isSelected()){
            bebida = "agua";
        } 
    }//GEN-LAST:event_Boton41ActionPerformed

    private void Boton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton43ActionPerformed
        // TODO add your handling code here:
        if (Boton43.isSelected()){
            bebida = "vino";
        } 
    }//GEN-LAST:event_Boton43ActionPerformed

    private void Boton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton42ActionPerformed
        // TODO add your handling code here:
        if (Boton42.isSelected()){
            bebida = "refresco";
        } 
    }//GEN-LAST:event_Boton42ActionPerformed

    private void Boton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton44ActionPerformed
        // TODO add your handling code here:
        if (Boton44.isSelected()){
            bebida = "cerveza";
        } 
    }//GEN-LAST:event_Boton44ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Boton11;
    private javax.swing.JRadioButton Boton12;
    private javax.swing.JRadioButton Boton13;
    private javax.swing.JRadioButton Boton21;
    private javax.swing.JRadioButton Boton22;
    private javax.swing.JRadioButton Boton23;
    private javax.swing.JRadioButton Boton31;
    private javax.swing.JRadioButton Boton32;
    private javax.swing.JRadioButton Boton33;
    private javax.swing.JRadioButton Boton41;
    private javax.swing.JRadioButton Boton42;
    private javax.swing.JRadioButton Boton43;
    private javax.swing.JRadioButton Boton44;
    private javax.swing.JButton Volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel erro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbdia;
    private javax.swing.JLabel lbhora;
    private javax.swing.JButton pedir;
    // End of variables declaration//GEN-END:variables
}
